config/routes.rb
Rails.application.routes.draw do

  resources :subscribers
  resources :comments
  resources :videos, only: [:show]
  resources :video_categories, only: [:index, :show]

  devise_for :administrators
  devise_for :users

  devise_scope :user do
    get "sign-in", to: "devise/sessions#new"
    get "sign-up", to: "devise/registrations#new"
  end

  namespace :admin do
    resources :videos
    resources :video_categories
    root to: 'videos#index'
  end

  root to: 'root#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :video
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to :back#, notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      redirect_to @comment, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy
    redirect_to comments_url, notice: 'Comment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def comment_params
      params.require(:comment).permit(:user_od, :body, :video_id)
    end
end

app/views/comments/_form.html.slim
= simple_form_for(@comment) do |f|
  = f.error_notification

  .form-inputs
    /= f.input :user_id
    = f.input :body
    = f.input :video_id

  .form-actions
    = f.button :submit

app/views/comments/edit.html.slim
h1 Editing comment

== render 'form'

= link_to 'Show', @comment
'|
= link_to 'Back', comments_path

app/views/comments/index.html.slim
h1 Listing comments

table
  thead
    tr
      th User od
      th Body
      th Video
      th
      th
      th

  tbody
    - @comments.each do |comment|
      tr
        td = comment.user_od
        td = comment.body
        td = comment.video_id
        td = link_to 'Show', comment
        td = link_to 'Edit', edit_comment_path(comment)
        td = link_to 'Destroy', comment, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.slim
h1 New comment

== render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.slim
p#notice = notice

p
  strong User od:
  = @comment.user_od
p
  strong Body:
  = @comment.body
p
  strong Video:
  = @comment.video_id

= link_to 'Edit', edit_comment_path(@comment)
'|
= link_to 'Back', comments_path