config/routes.rb
Rails.application.routes.draw do

  resources :subscribers
  resources :comments
  resources :videos, only: [:show]
  resources :video_categories, only: [:index, :show]

  devise_for :administrators
  devise_for :users

  devise_scope :user do
    get "sign-in", to: "devise/sessions#new"
    get "sign-up", to: "devise/registrations#new"
  end

  namespace :admin do
    resources :videos
    resources :video_categories
    root to: 'videos#index'
  end

  root to: 'root#index'
end

app/models/video_category.rb
class VideoCategory < ActiveRecord::Base
  validates :name, uniqueness: true

  has_many :videos

  def title
    self.name
  end

  def random_video
    offset = rand(self.videos.count)
    rand_record = self.videos.offset(offset).first
    rand_record
  end

  def random_video_link
    random_video.embed_link
  end

  #returns all category videos except one given video
  def other_videos video
    other_videos = self.videos.all
    other_videos.to_a.delete(video)  #removes video from listed videos
    other_videos
  end

  #returns 6 random videos, given video excluded
  def six_random_videos video
      videos = self.videos.all
      videos.to_a.delete(video)
      videos.sample(6)
  end

  def three_random_videos
      # videos = self.videos.sample(3)
      # videos.sample(3)
      self.videos.sample(3)
  end
end

app/controllers/admin/video_categories_controller.rb
class Admin::VideoCategoriesController < AdminController
  before_action :authenticate_administrator!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_video_category, only: [:show, :edit, :update, :destroy]

  # GET /video_categories
  def index
    @video_categories = VideoCategory.all
  end

  # GET /video_categories/1
  def show
    @videos_in_category = @video_category.videos
  end

  # GET /video_categories/new
  def new
    @video_category = VideoCategory.new
  end

  # GET /video_categories/1/edit
  def edit
  end

  # POST /video_categories
  def create
    @video_category = VideoCategory.new(video_category_params)

    if @video_category.save
      redirect_to @video_category, notice: 'Video category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /video_categories/1
  def update
    if @video_category.update(video_category_params)
      redirect_to @video_category, notice: 'Video category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /video_categories/1
  def destroy
    @video_category.destroy
    redirect_to video_categories_url, notice: 'Video category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video_category
      @video_category = VideoCategory.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def video_category_params
      params.require(:video_category).permit(:name)
    end
end

app/controllers/video_categories_controller.rb
class VideoCategoriesController < ApplicationController
  before_action :authenticate_administrator!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_video_category, only: [:show, :edit, :update, :destroy]

  # GET /video_categories
  def index
    @video_categories = VideoCategory.all
  end

  # GET /video_categories/1
  def show
    @videos_in_category = @video_category.videos
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video_category
      @video_category = VideoCategory.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def video_category_params
      params.require(:video_category).permit(:name)
    end
end

app/helpers/video_categories_helper.rb
module VideoCategoriesHelper
  def categories
    VideoCategory.all
  end
end

app/views/admin/video_categories/_form.html.slim
= simple_form_for [:admin, @video_category] do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/admin/video_categories/admin.html.slim
- meta title: 'All categories'

.container
  h1 Listing video_categories

  table
    thead
      tr
        th Name
        th
        th
        th

    tbody
      - @video_categories.each do |video_category|
        tr
          td = video_category.name
          td = link_to 'Show', admin_video_category_path(video_category)
          td = link_to 'Edit', edit_admin_video_category_path(video_category)
          td = link_to 'Destroy', destroy_admin_video_category_path(video_category), data: {:confirm => 'Are you sure?'}, :method => :delete

  br

  = link_to 'New Video category', new_admin_video_category_path

app/views/admin/video_categories/edit.html.slim
.heading
  h1 Editing video category
  .buttons-wrapper
    = link_to @video_category, class: 'btn btn-warning'
      i.glyphicon.glyphicon-play
      | Show category videos
    = link_to admin_video_categories_path, class: 'btn btn-default'
      i.glyphicon.glyphicon-menu-left
      | Back to all video categories

= render 'form'

app/views/admin/video_categories/index.html.slim
- meta title: 'All categories'

.heading
  h1 Listing video categories
  .buttons-wrapper
    = link_to new_admin_video_category_path, class: 'btn btn-success'
      i.glyphicon.glyphicon-plus
      | New video category

.videos-overview
  table.table-admin.table.table-striped.table-bordered
    thead
      tr
        th ID
        th Name
        th colspan="3" Actions

    tbody
      - @video_categories.each do |video_category|
        tr
          td = video_category.id
          td = video_category.name
          td.centered
            = link_to video_category_path(video_category), data: { :toggle => 'tooltip',
                                     :title => 'Show category videos' }
              i.glyphicon.glyphicon-play
          td.centered
            = link_to edit_admin_video_category_path(video_category), data: { :toggle => 'tooltip',
                                                     :title => 'Edit' }
              i.glyphicon.glyphicon-edit
          td.centered
            = link_to video_category, data: { :confirm => 'Are you sure?',
                                     :toggle => 'tooltip',
                                     :title => 'Delete' },
                                     :method => :delete
              i.glyphicon.glyphicon-trash

app/views/admin/video_categories/new.html.slim
.heading
  h1 New video category
  .buttons-wrapper
    = link_to admin_video_categories_path, class: 'btn btn-default'
      i.glyphicon.glyphicon-menu-left
      | Back to all videos

= render 'form'

app/views/admin/video_categories/show.html.slim
- meta title: @video_category.title + ' category'
- wide_screen(true)

.big-heading
  .container
    h2
      =< @video_category.title

.container
  - main_video = @video_category.random_video
  = render 'partials/main_video', video: main_video, source: nil

  .categories-wrapper
    .another-videos
      .category-video-heading
        h2 Another category videos
    - @video_category.six_random_videos(main_video).each do |video|
      = render 'partials/common_video', video:    video,
                                        category: nil