config/routes.rb
Rails.application.routes.draw do

  resources :subscribers
  resources :comments
  resources :videos, only: [:show]
  resources :video_categories, only: [:index, :show]

  devise_for :administrators
  devise_for :users

  devise_scope :user do
    get "sign-in", to: "devise/sessions#new"
    get "sign-up", to: "devise/registrations#new"
  end

  namespace :admin do
    resources :videos
    resources :video_categories
    root to: 'videos#index'
  end

  root to: 'root#index'
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :set_subscriber, only: [:show, :edit, :update, :destroy]

  # GET /subscribers
  def index
    @subscribers = Subscriber.all
  end

  # GET /subscribers/1
  def show
  end

  # GET /subscribers/new
  def new
    @subscriber = Subscriber.new
  end

  # GET /subscribers/1/edit
  def edit
  end

  # POST /subscribers
  def create
    @subscriber = Subscriber.new(subscriber_params)

    if @subscriber.save
      redirect_to root_path, notice: 'Subscriber was successfully created.'
    else
      redirect_to Video.find(1), alert: 'Please insert valid email.'
    end
  end

  # PATCH/PUT /subscribers/1
  def update
    if @subscriber.update(subscriber_params)
      redirect_to root_path, notice: 'Subscriber was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /subscribers/1
  def destroy
    @subscriber.destroy
    redirect_to subscribers_url, notice: 'Subscriber was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscriber
      @subscriber = Subscriber.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def subscriber_params
      params.require(:subscriber).permit(:email)
    end
end

app/views/subscribers/_form.html.slim
= simple_form_for(@subscriber) do |f|
  = f.error_notification

  .form-inputs
    = f.input :email

  .form-actions
    = f.button :submit

app/views/subscribers/edit.html.slim
h1 Editing subscriber

== render 'form'

= link_to 'Show', @subscriber
'|
= link_to 'Back', subscribers_path

app/views/subscribers/index.html.slim
h1 Listing subscribers

table
  thead
    tr
      th Email
      th
      th
      th

  tbody
    - @subscribers.each do |subscriber|
      tr
        td = subscriber.email
        td = link_to 'Show', subscriber
        td = link_to 'Edit', edit_subscriber_path(subscriber)
        td = link_to 'Destroy', subscriber, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Subscriber', new_subscriber_path

app/views/subscribers/new.html.slim
h1 New subscriber

== render 'form'

= link_to 'Back', subscribers_path

app/views/subscribers/show.html.slim
p#notice = notice

p
  strong Email:
  = @subscriber.email

= link_to 'Edit', edit_subscriber_path(@subscriber)
'|
= link_to 'Back', subscribers_path