config/routes.rb
Rails.application.routes.draw do

  resources :subscribers
  resources :comments
  resources :videos, only: [:show]
  resources :video_categories, only: [:index, :show]

  devise_for :administrators
  devise_for :users

  devise_scope :user do
    get "sign-in", to: "devise/sessions#new"
    get "sign-up", to: "devise/registrations#new"
  end

  namespace :admin do
    resources :videos
    resources :video_categories
    root to: 'videos#index'
  end

  root to: 'root#index'
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :video_categories
  has_many :comments
  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  VIMEO_LINK_FORMAT = /(?:vimeo(?:-nocookie)?\.com\/)(([0-9]{8})|([0-9]{9}))/i
  
  VIMEO_LINK_FORMAT2 = /https?:\/\/(?:www\.|player\.)?vimeo.com\/(?:channels\/(?:\w+\/)?|groups\/([^\/]*)\/videos\/|album\/(\d+)\/video\/|video\/|)(\d+)(?:$|\/|\?)/i
  
  YT_LINK_FORMAT = /(?:youtube(?:-nocookie)?\.com\/(?:[^\/]+\/.+\/|(?:v|e(?:mbed)?)\/|.*[?&]v=)|youtu\.be\/)([^"&?\/ ]{11})/i

  YT_VIMEO_LINK_FORMAT = /((?:vimeo(?:-nocookie)?\.com\/)((\d{8})|(\d{9})))|((?:youtube(?:-nocookie)?\.com\/(?:[^\/]+\/.+\/|(?:v|e(?:mbed)?)\/|.*[?&]v=)|youtu\.be\/)([^"&?\/ ]{11}))/i

  validates :link, presence: true, format: YT_VIMEO_LINK_FORMAT
  validates :video_category_id, presence: true

  def set_thumbnail_image url
    self.image = URI.parse(url)
  end

  def set_thumbnail_image_seed file
    self.image = file
  end

  def category
    VideoCategory.find(self.video_category_id)
  end

  def youtube_id
    self.link.split("=").last
  end
  
  def thumbnail
    if Rails.env == 'production'
      VideoInfo.new(self.link).thumbnail_large
    else
      self.image
    end
  end

  def embed_link
    VideoInfo.new(self.link).embed_url
  end

  def Video.random_video
    offset = rand(Video.count)
    Video.offset(offset).first
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < AdminController
  before_action :authenticate_administrator!, only: [:index, :new, :edit, :create, :update, :destroy]
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  layout 'admin'

  # GET /videos
  def index
    @videos = Video.all.page params[:page]
  end

  # GET /videos/1
  def show
    @comments = @video.comments.all
    @comment = @video.comments.build
    #@comment = Comment.new
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  def create
    @video = Video.new(video_params)

    if @video.save
      video_info = VideoInfo.new(@video.link)
      @video.set_thumbnail_image(video_info.thumbnail_large)

      if @video.title == "" then
        @video.title = video_info.title
      end
      @video.save
      redirect_to @video, notice: 'Video was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /videos/1
  def update
    if @video.update(video_params)
      redirect_to @video, notice: 'Video was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /videos/1
  def destroy
    @video.destroy
    redirect_to videos_url, notice: 'Video was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def video_params
      params.require(:video).permit(:title, :link, :video_category_id)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show]


  # GET /videos/1
  def show
    @comments = @video.comments.all
    @comment = @video.comments.build
    #@comment = Comment.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def video_params
      params.require(:video).permit(:title, :link, :video_category_id)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
  def embed(youtube_url)
    youtube_id = youtube_url.split("=").last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
  end

  def categories_collection
    VideoCategory.order(:name)
  end

  def main_video
    Video.random_video
  end
end

app/views/admin/videos/_form.html.slim
= simple_form_for [:admin, @video] do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :link
    = f.input :video_category_id, collection: VideoCategory.all
  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/admin/videos/edit.html.slim
.heading
  h1 Editing video
  .buttons-wrapper
    = link_to @video, class: 'btn btn-warning'
      i.glyphicon.glyphicon-play
      | Play video
    = link_to admin_videos_path, class: 'btn btn-default'
      i.glyphicon.glyphicon-menu-left
      | Back to all videos

= render 'form'

app/views/admin/videos/index.html.slim
.heading
  h1 Listing videos
  .buttons-wrapper
    = link_to new_admin_video_path, class: 'btn btn-success'
      i.glyphicon.glyphicon-plus
      | New video

.videos-overview
  table.table-admin.table.table-striped.table-bordered
    thead
      tr
        th Title
        th Category
        th Link
        th colspan="3" Actions

    tbody
      - @videos.each do |video|
        tr
          td = video.title
          td = video.category.name
          td.centered
            = link_to video.link, data: { :toggle => 'tooltip',
                                          :title => 'URL to provider' }
              i.glyphicon.glyphicon-expand
          td.centered
            = link_to video_path(video), data: { :toggle => 'tooltip',
                                     :title => 'Play video' }
              i.glyphicon.glyphicon-play
          td.centered
            = link_to edit_admin_video_path(video), data: { :toggle => 'tooltip',
                                                     :title => 'Edit' }
              i.glyphicon.glyphicon-edit
          td.centered
            = link_to video, data: { :confirm => 'Are you sure?',
                                     :toggle => 'tooltip',
                                     :title => 'Delete' },
                                     :method => :delete
              i.glyphicon.glyphicon-trash

  .pagination-wrapper
    = paginate @videos, :window => 2

app/views/admin/videos/new.html.slim
.heading
  h1 New video
  .buttons-wrapper
    = link_to admin_videos_path, class: 'btn btn-default'
      i.glyphicon.glyphicon-menu-left
      | Back to all videos

= render 'form'

app/views/admin/videos/show.html.slim
- meta title: @video.title
- wide_screen(true)

= render 'partials/main_video', video: @video, source: 'detail'

.container
  .detail-category
    strong Category:
    =< link_to @video.category.name, VideoCategory.find(@video.video_category_id)

.container
  .categories-wrapper
    .another-videos
      .category-video-heading
        h2 Another similar videos
    - @video.category.six_random_videos(@video).each do |video|
      = render 'partials/common_video', video:    video,
                                        category: nil